测试驱动开发：
第一步，让其失败
H:\dxy\Python2011testingcookbook\Pytest\test\chapter06>pytest -vs test_module01.py
============================= test session starts =============================
platform win32 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- c:\python27\python.exe
cachedir: ..\..\..\.cache
metadata: {'Python': '2.7.13', 'Platform': 'Windows-7-6.1.7601-SP1', 'Packages': {'py': '1.4.34', 'pytest': '3.1.3', 'pluggy': '0.4.0'}, 'JAVA_HOME': 'C:\\Program Files\\J
ava\\jdk1.8.0_101', 'Plugins': {'pythonpath': '0.7', 'html': '1.15.1', 'xdist': '1.14', 'cov': '2.3.0', 'metadata': '1.5.0'}}
rootdir: H:\dxy\Python2011testingcookbook, inifile:
plugins: xdist-1.14, pythonpath-0.7, metadata-1.5.0, html-1.15.1, cov-2.3.0
collected 1 item s

test_module01.py::TestClass01::test_case01 FAILED

================================== FAILURES ===================================
___________________________ TestClass01.test_case01 ___________________________

self = <test_module01.TestClass01 instance at 0x000000000397ED48>

    def test_case01(self):
>       calc = Calculator()
E       NameError: global name 'Calculator' is not defined

test_module01.py:5: NameError
============================== warnings summary ===============================
None
  pytest_funcarg__cov: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @p
ytest.fixture decorator instead.

-- Docs: http://doc.pytest.org/en/latest/warnings.html
==================== 1 failed, 1 warnings in 0.08 seconds =====================

H:\dxy\Python2011testingcookbook\Pytest\test\chapter06>
第二步，让其成功
返回信息提示没有计算函数，那就构造一个Calculator.py
再次执行：没有任何返回值的，
class Calculator:
    def add(self,x,y):
        pass

_________________________ TestClass01.test_case01 ___________________________

self = <test_module01.TestClass01 instance at 0x0000000003AB2FC8>

    def test_case01(self):
        calc = Calculator()
        result = calc.add(2,2)
>       assert  4 == result
E       assert 4 == None

test_module01.py:8: AssertionError
============================== warnings summary ===============================
None
  pytest_funcarg__cov: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @p
ytest.fixture decorator instead.

-- Docs: http://doc.pytest.org/en/latest/warnings.html
==================== 1 failed, 1 warnings in 0.08 seconds =====================

H:\dxy\Python2011testingcookbook\Pytest\test\chapter06>
********************************************************************************************

第三步，修改导入模块中的类返回值，pass改为 return x+y
再次执行
test_module01.py::TestClass01::test_case01 PASSED

============================== warnings summary ===============================
None
  pytest_funcarg__cov: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @p
ytest.fixture decorator instead.

-- Docs: http://doc.pytest.org/en/latest/warnings.html
==================== 1 passed, 1 warnings in 0.06 seconds =====================

H:\dxy\Python2011testingcookbook\Pytest\test\chapter06>
第四步，修改测试模块，增加测试模块功能继续上述步骤